packages:
  - 'packages/*'
  - 'packages/inlang/*'
  - 'packages/inlang/plugins/*'
  - 'packages/inlang/*/example'
  - 'packages/inlang/*/examples/*'
  - 'packages/*/example'
  - 'packages/*/examples/*'
  