packages:
  - 'inlang/source-code/plugins/*'
  - 'packages/*'
  - 'packages/inlang/*'
  - 'packages/inlang/*/example'
  - 'packages/inlang/*/examples/*'
  - 'packages/*/example'
  - 'packages/*/examples/*'
  